language: ruby
rvm:
  - jruby-19mode
jdk:
  - openjdk6
  - oraclejdk7
script: rake $TASK
env:
  - TASK=bytecode_ci
  - TASK=new_ci
matrix:
  allow_failures:
    - env: TASK=new_ci
notifications:
  irc: "irc.freenode.org#mirah"